#!/bin/bash

echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "<meta http-equiv=\"Content-type\" content=\"text/html;charset=UTF-8\" />"
echo "</head>"
echo "<body>"

ZOZ=false

while IFS= read LINE
do

    if [[ "$LINE" =~ ^[[:space:]]*$ ]]; then 
        echo "<p></p>"
        continue
    fi
    
    if [[ $LINE =~ ^#\ +(.+)$ ]]; then
        echo "<h1>${BASH_REMATCH[1]}</h1>"
        continue
    elif [[ $LINE =~ ^##\ +(.+)$ ]]; then
        echo "<h2>${BASH_REMATCH[1]}</h2>"
        continue
    #druha uloha    
    elif echo "$LINE" | grep -q '^[[:space:]]*-[[:space:]]'; then
        if ! $ZOZ; then
            echo "<ul>"
            ZOZ=true  
        fi 
        text=$(echo "$LINE" | sed -E 's/^[[:space:]]*-[[:space:]]+(.*)$/<li>\1<\/li>/')
        echo "$text"
    else 
        if $ZOZ; then
            echo "</ul>"
            ZOZ=false
        fi
    
        #prva uloha
        LINE=$(echo "$LINE" | sed 's@<https://\([^>]*\)>@<a href="https://\1">https://\1</a>@g')

        LINE=$(echo "$LINE" | sed -E 's/__([^_]+)__/\<strong\>\1\<\/strong\>/g')
        LINE=$(echo "$LINE" | sed -E 's/_([^_]+)_/\<em\>\1\<\/em\>/g')

        echo "$LINE"
    fi
done

if $ZOZ
    then
    echo "</ul>"
fi

echo "</body>"
echo "</html>"
